name: asfdfmtl
channels:
  - nvidia
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pip 
  - pytorch=2.4.1
  - torchaudio=2.4.1
  - torchvision=0.19.1
  - tqdm=4.66.4
  - matplotlib=3.7.2
  - scipy=1.10.1
  - pandas=2.0.3
  - pip:
      - black==24.8.0
      - flake8==7.1.1
      - torchmetrics==1.4.1
      - gdown==5.2.0